### ISSUE TITLE
TCP Connection Configuration?

### ISSUE THREAD

**Issue by corwin-of-amber** [philpennock/vlc-control#1]
This is not an issue with the code itself but more on the instructions. I noticed that you are connecting to VLC via TCP and also running on a Mac. I've been driven to frustration trying to make my VLC accept TCP connections:
 * When I run VLC from the command line with `-I oldrc` etc., it seems to accept connections but does not create a window and cannot play video.
 * When I run VLC normally and check the RC interface in "Main Interfaces", nothing happens!

I have twiddled with the various configuration options quite a bit but there is virtually no help on the Web, at least as far as Mac OS is concerned. Can you include some directions in your Readme?

**Comment by philpennock** [comment]
Does the change in #2 provide suitable documentation?

**Comment by philpennock** [comment]
(Until merged and the branch is deleted, the results of the markdown changes are viewable at:
https://github.com/philpennock/vlc-control/blob/docs-vlc/README.md
)

**Comment by corwin-of-amber** [comment]
This is perfect! These were exactly the missing bits.
It's definitely missing from the VLC documentation, so at least now it would appear *somewhere*.
